language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
- composer install --no-progress

script:
- composer normalize --dry-run
- ./vendor/bin/phpcs
- ./vendor/bin/phpstan analyse -c phpstan.neon
- ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
